DROP  TRIGGER TR_SIP_DEPTO_AUTONUMERACAO;
DROP SEQUENCE SQ_SIP_CD_DEPTO;
TRUNCATE TABLE T_SIP_DEPTO;


CREATE SEQUENCE SQ_SIP_CD_DEPTO
START WITH 1
MAXVALUE 7;

INSERT INTO T_SIP_DEPTO (CD_DEPTO,NM_DEPTO,SG_DEPTO)
VALUES(SQ_SIP_CD_DEPTO.NEXTVAL,'AMBULATORIO','AMB');

INSERT INTO T_SIP_DEPTO (CD_DEPTO,NM_DEPTO,SG_DEPTO)
VALUES(SQ_SIP_CD_DEPTO.NEXTVAL,'CIPA','CIP');

--MOSTRA SEQUENCE
SELECT SQ_SIP_CD_DEPTO.CURRVAL FROM DUAL; 

-- ALTERANDO O VALOR MAX DA SEQUENCE
ALTER SEQUENCE SQ_SIP_CD_DEPTO MAXVALUE 99;

--TABELA NATIVA ORACLE
SELECT*FROM DUAL;

--SABER O DIA DE NASCIMENTO 
SELECT TO_CHAR(TO_DATE('19/11/1971','DD/MM/YYYY'),'DAY') FROM DUAL;

SELECT TO_CHAR(TO_DATE('25/10/1988','DD/MM/YYYY'),'DAY') FROM DUAL;

CREATE SEQUENCE SQ_SIP_FUNCIONARIO
START WITH 1;

INSERT INTO T_SIP_FUNCIONARIO(NR_MATRICULA,CD_DEPTO,NM_FUNCIONARIO,DT_NASCIMENTO,DT_ADMISSAO,VL_SALARIO)VALUES(SQ_SIP_FUNCIONARIO.NEXTVAL,1,'FILIPE',
SYSDATE -10000,SYSDATE,DBMS_RANDOM.VALUE(28000,53000));

SELECT *FROM T_SIP_FUNCIONARIO;


--MULTI INSERT

INSERT ALL
    INTO T_SIP_DEPTO (CD_DEPTO,NM_DEPTO,SG_DEPTO)
    VALUES(SQ_SIP_CD_DEPTO.NEXTVAL,'METAVERSO','MTV')
    INTO T_SIP_FUNCIONARIO(NR_MATRICULA,CD_DEPTO,NM_FUNCIONARIO,DT_NASCIMENTO,DT_ADMISSAO,VL_SALARIO)VALUES(SQ_SIP_FUNCIONARIO.NEXTVAL,SQ_SIP_CD_DEPTO.CURRVAL,'FILIPE',
    SYSDATE -10000,SYSDATE,DBMS_RANDOM.VALUE(28000,53000))
    
    INTO T_SIP_DEPENDENTE(NR_MATRICULA,CD_DEPENDENTE,NM_DEPENDENTE,DT_NASCIMENTO)VALUES(SQ_SIP_FUNCIONARIO.CURRVAL,1,'GUSTAVO',SYSDATE-3650)
    INTO T_SIP_DEPENDENTE(NR_MATRICULA,CD_DEPENDENTE,NM_DEPENDENTE,DT_NASCIMENTO)VALUES(SQ_SIP_FUNCIONARIO.CURRVAL,2,'GUSTAVO',SYSDATE-3650)
SELECT * FROM DUAL;    
    
--AUTOMAÇÃO DA SEQUENCE
--OBJETOS EM BANCO DE DADOS 

CREATE OR REPLACE TRIGGER TR_SIP_DEPTO_AUTONUMERACAO
BEFORE INSERT ON T_SIP_DEPTO FOR EACH ROW
BEGIN
    :NEW.CD_DEPTO :=SQ_SIP_CD_DEPTO.NEXTVAL;
END;
/

INSERT INTO T_SIP_DEPTO (NM_DEPTO,SG_DEPTO)
VALUES('DIRETORIA','DIT');
--CRICAO DE AUTOMACAO 



   